Wazo 2764 stasis unsubscribe
wazo-platform/wazo-res-stasis-amqp pull request #34
Opened 2022-05-10 15:28 UTC by pc-m

2022-05-17 19:18 UTC, bloom1 requested changes

2022-05-17 19:18 UTC, bloom1 commented on resource_amqp.h
> + * Delete a Stasis application and subscribe to it's event and forward them to AMQP. The application's name must be unique.
Nitpicking: `it's event` => `its events`

2022-05-17 19:18 UTC, bloom1 commented on amqp.json
> +					"notes": "Delete a Stasis application and subscribe to it's event and forward them to AMQP. The application's name must be unique.",
Nitpicking: `it's event` => `its events`

2022-05-17 19:18 UTC, bloom1 commented on res_ari_amqp.c
> + * Wazo
Isn't that redundant with the copyright line?

2022-05-17 19:18 UTC, bloom1 commented on resource_amqp.c
> + * Wazo
Same as previous comment about copyright

2022-05-17 19:18 UTC, bloom1 commented on resource_amqp.h
> + * Wazo
Same as previous comment about copyright

2022-05-17 19:18 UTC, bloom1 commented on res_ari_amqp.c
> +	return;
What is the purpose of this?

2022-05-18 12:59 UTC, pc-m commented on res_ari_amqp.c
> + * Wazo
It's auto-generated code from the template which uses the `_author` field

2022-05-18 13:03 UTC, pc-m commented on res_ari_amqp.c
> +	return;
The `fin` label is auto-generated from the template. the `__attribute__((unused))` prevents the compiler from generating a warning when the label is unused.

2022-05-18 13:04 UTC, bloom1 commented on res_ari_amqp.c
> +	return;
Thank you!

2022-05-18 19:29 UTC, bloom1 approved these changes

2022-05-18 19:36 UTC, merged